server {
    teams{
        share notes with a team
        share notes with the public
    }
    gamification {
        leaderboard {
            collaboration efforts
            learning effords
            consistency
            
        }
    }
    llm{
        create notes  inputs

    }

    moodle{
        plugin
        create teams and decks automatically based on moodle content
    }
    browser extention

}



student{
    client
    PDFs
    ebooks
    youtube 
    podcasts
    blogs
    teammmemberships
    data{
        uni{
            location
            course
            semester
            university

        }
        competences{
            competence paths 
        }
        educational content {
            learn every key insight from a piece of content
        }
    }

}